from pathlib import Path
import re
p=Path('reporte-trabajo.html')
s=p.read_text(encoding='utf-8')
# Mantener una hoja A4 física.
s=s.replace('.sheet{width:210mm;min-height:297mm;', '.sheet{width:210mm;height:297mm;min-height:297mm;max-height:297mm;')
# En móvil NO refluye el documento: se conserva la composición A4 y se escala completo.
s=re.sub(r'@media\(max-width:900px\)\{.*?\}@media print', '@media(max-width:900px){html,body{width:100%;max-width:100%;overflow-x:hidden}body{padding:8px;background:#dfe5ea}.toolbar{width:calc(100% - 4px);max-width:520px;grid-template-columns:1fr;gap:6px;margin:0 auto 10px}.toolbar button{font-size:13px;padding:10px 8px}.sheet{width:210mm!important;height:297mm!important;min-height:297mm!important;max-height:297mm!important;padding:9mm 10mm!important;margin:0!important}.header{grid-template-columns:72mm 1fr!important}.logo{width:66mm!important}.summary{grid-template-columns:repeat(4,1fr)!important}.service,.panels{grid-template-columns:1fr 1fr!important}.svcCol+.svcCol{border-left:1px solid #d7e2ea!important;border-top:0!important;padding-left:6mm!important;margin-top:0!important;padding-top:0!important}.evidenceGrid{grid-template-columns:repeat(5,1fr)!important}.evImg,.evMissing{height:31mm!important}.a4-stage{position:relative;overflow:hidden;margin:0 auto 14px!important}}@media print', s, flags=re.S)
# Reemplazar lógica anterior si ya fue inyectada.
s=re.sub(r'<style id="a4PreviewPatch">.*?</script>', '', s, flags=re.S)
addon='''<style id="a4PreviewPatch">.a4-stage{position:relative;margin:0 auto 18px;overflow:hidden}.sheet{transform-origin:top left}.preview-note{max-width:210mm;margin:0 auto 8px;text-align:center;color:#667985;font-size:12px}@media print{.a4-stage{width:auto!important;height:auto!important;overflow:visible!important;margin:0!important}.sheet{transform:none!important}.preview-note{display:none!important}}</style><script id="a4PreviewLogic">function ajustarHojaA4(){const hoja=document.querySelector('.sheet');if(!hoja)return;let stage=hoja.parentElement;if(!stage.classList.contains('a4-stage')){stage=document.createElement('div');stage.className='a4-stage';hoja.parentNode.insertBefore(stage,hoja);stage.appendChild(hoja)}hoja.style.transform='none';hoja.style.transformOrigin='top left';stage.style.width='auto';stage.style.height='auto';const naturalW=hoja.offsetWidth,naturalH=hoja.offsetHeight;const viewport=Math.max(280,document.documentElement.clientWidth||window.innerWidth);const margen=16;const escala=Math.min(1,(viewport-margen)/naturalW);const ancho=Math.floor(naturalW*escala);const alto=Math.ceil(naturalH*escala);stage.style.width=ancho+'px';stage.style.height=alto+'px';stage.style.marginLeft='auto';stage.style.marginRight='auto';hoja.style.transform='scale('+escala+')';const cont=document.getElementById('contenido');if(cont){cont.style.zoom='1';requestAnimationFrame(()=>{const disponible=hoja.clientHeight-4;const usado=cont.scrollHeight;if(usado>disponible){const z=Math.max(.68,disponible/usado);cont.style.zoom=String(z)}})}}window.addEventListener('resize',()=>requestAnimationFrame(ajustarHojaA4));window.addEventListener('orientationchange',()=>setTimeout(ajustarHojaA4,120));window.addEventListener('load',()=>setTimeout(ajustarHojaA4,250));const _obs=new MutationObserver(()=>setTimeout(ajustarHojaA4,30));window.addEventListener('DOMContentLoaded',()=>{const c=document.getElementById('contenido');if(c)_obs.observe(c,{childList:true,subtree:true})});</script>'''
if '</body>' in s:
    s=s.replace('</body>',addon+'</body>',1)
p.write_text(s,encoding='utf-8')
