from pathlib import Path
import re
p=Path('reporte-trabajo.html')
s=p.read_text(encoding='utf-8')
# Hoja A4 real flotante, nunca convertida en pantalla larga.
s=s.replace('.sheet{width:210mm;min-height:297mm;', '.sheet{width:210mm;height:297mm;min-height:297mm;max-height:297mm;')
s=s.replace('overflow:hidden}.sheet:after', 'overflow:hidden}.sheet:after')
# En móvil mantener proporción A4; el escalado lo maneja JS.
s=re.sub(r'@media\(max-width:900px\)\{.*?\}@media print', '@media(max-width:900px){body{padding:10px;background:#dfe5ea}.toolbar{grid-template-columns:1fr 1fr 1fr;gap:6px}.toolbar button{font-size:12px;padding:10px 6px}.sheet{width:210mm!important;height:297mm!important;min-height:297mm!important;max-height:297mm!important;padding:9mm 10mm!important;margin:0!important}.header{grid-template-columns:72mm 1fr!important}.logo{width:66mm!important}.summary{grid-template-columns:repeat(4,1fr)!important}.service,.panels{grid-template-columns:1fr 1fr!important}.svcCol+.svcCol{border-left:1px solid #d7e2ea!important;border-top:0!important;padding-left:6mm!important;margin-top:0!important;padding-top:0!important}.evidenceGrid{grid-template-columns:repeat(5,1fr)!important}.evImg,.evMissing{height:31mm!important}.a4-stage{width:100%;display:flex;justify-content:center;align-items:flex-start;overflow:visible}}@media print', s, flags=re.S)
# Compactar un poco para asegurar una sola hoja y añadir stage flotante + ajuste automático.
addon='''<style id="a4PreviewPatch">.a4-stage{position:relative;margin:0 auto 18px;display:flex;justify-content:center;align-items:flex-start}.sheet{transform-origin:top center}.sheet.a4-fit #contenido{transform-origin:top left}.preview-note{max-width:210mm;margin:0 auto 8px;text-align:center;color:#667985;font-size:12px}@media print{.a4-stage{height:auto!important;display:block!important}.sheet{transform:none!important}.preview-note{display:none!important}}</style><script id="a4PreviewLogic">function ajustarHojaA4(){const hoja=document.querySelector('.sheet');if(!hoja)return;let stage=hoja.parentElement;if(!stage.classList.contains('a4-stage')){stage=document.createElement('div');stage.className='a4-stage';hoja.parentNode.insertBefore(stage,hoja);stage.appendChild(hoja)}hoja.style.transform='none';stage.style.height='auto';const naturalW=hoja.offsetWidth,naturalH=hoja.offsetHeight;const margen=20;const escala=Math.min(1,(window.innerWidth-margen)/naturalW);hoja.style.transform='scale('+escala+')';stage.style.height=(naturalH*escala)+'px';stage.style.width='100%';const cont=document.getElementById('contenido');if(cont){cont.style.zoom='1';requestAnimationFrame(()=>{const disponible=hoja.clientHeight-4;const usado=cont.scrollHeight;if(usado>disponible){const z=Math.max(.72,disponible/usado);cont.style.zoom=String(z)}})}}window.addEventListener('resize',ajustarHojaA4);window.addEventListener('load',()=>setTimeout(ajustarHojaA4,250));const _obs=new MutationObserver(()=>setTimeout(ajustarHojaA4,30));window.addEventListener('DOMContentLoaded',()=>{const c=document.getElementById('contenido');if(c)_obs.observe(c,{childList:true,subtree:true})});</script>'''
if 'a4PreviewPatch' not in s:
    s=s.replace('</body>',addon+'</body>',1)
p.write_text(s,encoding='utf-8')
