const API='https://ajnbswrwnjpjypjiorye.supabase.co/functions/v1/inventario-conciliacion-tecnica',KEY='disprotel_login_general_v2';
let me={};try{me=JSON.parse(sessionStorage.getItem(KEY)||'{}')}catch{}
const H=()=>({'Content-Type':'application/json','x-user':me.usuario||'','x-pin':me.pin||'','x-session':me.session_token||''});
const n=s=>String(s||'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').trim().toUpperCase(),e=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
let rows=[],lote=null,meta=null;
async function call(b){const r=await fetch(API,{method:'POST',headers:H(),body:JSON.stringify(b)}),d=await r.json().catch(()=>({}));if(!r.ok||d.error)throw Error(d.error||'Error');return d}
function msg(t,k=''){const x=document.getElementById('msg');x.textContent=t;x.className='status '+k}
function map(o){const m={};for(const k of Object.keys(o||{}))m[n(k).replace(/[^A-Z0-9]/g,'')]=k;return m}
function pick(o,m,ks){for(const k of ks){const z=m[k];if(z!=null&&String(o[z]??'').trim())return o[z]}return ''}
function one(o,i){const m=map(o),router=pick(o,m,['ROUTER','ROUTERLEGACY','ROUTERACTUALSUGERIDO','RB','NODO']);return{fila_origen:i+2,codigo_servicio:pick(o,m,['CODIGOSERVICIOLEGACY','CODIGOSERVICIO','CODIGO','SERVICIO','IDSERVICIO']),identificacion:pick(o,m,['IDENTIFICACION','CEDULA','RUC','DOCUMENTO']),cliente:pick(o,m,['CLIENTE','NOMBRECLIENTE','NOMBRE','TITULAR']),router,ciudad:pick(o,m,['CIUDAD','CANTON','ZONA']),tipo_conexion:pick(o,m,['TIPOCONEXION','TIPOSERVICIO','CONEXION','TIPO']),ip_cliente:String(pick(o,m,['IPCLIENTE','IP','DIRECCIONIP','ADDRESS'])||'').replace(/\/\d+$/,'').trim(),plan:pick(o,m,['PLAN','PLANCODIGO','PLANINTERNET','VELOCIDAD']),direccion:pick(o,m,['DIRECCION','DIRECCIONSERVICIO','DOMICILIO']),raw:o}}
function stats(){const f=rows.filter(x=>/FIBRA|GPON|FTTH/i.test(x.tipo_conexion)).length,r=rows.filter(x=>/RADIO|ANTENA|WIRELESS/i.test(x.tipo_conexion)).length,rs=new Set(rows.map(x=>n(x.router)).filter(Boolean));cTotal.textContent=rows.length;cFibra.textContent=f;cRadio.textContent=r;cRouters.textContent=rs.size}
function preview(){document.getElementById('preview').innerHTML=rows.length?rows.slice(0,300).map(x=>'<tr><td>'+x.fila_origen+'</td><td>'+e(x.codigo_servicio)+'</td><td>'+e(x.cliente)+'</td><td>'+e(x.router)+'</td><td>'+e(x.tipo_conexion)+'</td><td>'+e(x.ip_cliente)+'</td><td>'+e(x.plan)+'</td><td>'+e(x.direccion)+'</td></tr>').join(''):'<tr><td colspan="8">Sin filas.</td></tr>'}
async function readFile(f){msg('Leyendo '+f.name+'…');meta={name:f.name,type:f.type};const b=await f.arrayBuffer(),wb=XLSX.read(b,{type:'array'}),raw=XLSX.utils.sheet_to_json(wb.Sheets[wb.SheetNames[0]],{defval:''});rows=raw.map(one).filter(x=>x.codigo_servicio||x.cliente||x.ip_cliente);lote=null;stats();preview();save.disabled=!rows.length;reconcile.disabled=true;msg('Archivo listo: '+rows.length+' servicios reconocidos.','ok')}
file.onchange=()=>file.files[0]&&readFile(file.files[0]).catch(x=>msg(x.message,'err'));
['dragenter','dragover'].forEach(v=>drop.addEventListener(v,x=>{x.preventDefault();drop.classList.add('drag')}));['dragleave','drop'].forEach(v=>drop.addEventListener(v,x=>{x.preventDefault();drop.classList.remove('drag')}));drop.ondrop=x=>{const f=x.dataTransfer.files[0];if(f)readFile(f).catch(y=>msg(y.message,'err'))};
save.onclick=async()=>{try{save.disabled=true;save.textContent='Guardando…';const d=await call({action:'upload',archivo_nombre:meta?.name||'archivo.xlsx',archivo_tipo:meta?.type||'',rows});lote=d.lote_id;reconcile.disabled=false;msg('Lote guardado. Ya puedes conciliar.','ok');await history()}catch(x){msg(x.message,'err')}finally{save.disabled=false;save.textContent='Guardar lote'}};
reconcile.onclick=async()=>{try{if(!lote)throw Error('Primero guarda el lote');reconcile.disabled=true;reconcile.textContent='Conciliando…';await call({action:'reconcile',lote_id:lote});await openLote(lote);show('result');msg('Conciliación terminada.','ok');await history()}catch(x){msg(x.message,'err')}finally{reconcile.disabled=false;reconcile.textContent='Ejecutar conciliación'}};
clear.onclick=()=>{rows=[];lote=null;file.value='';stats();preview();save.disabled=true;reconcile.disabled=true;msg('Sin archivo cargado.')};
function cls(r){return /^OK_/.test(r)?'ok':/SIN_|DUPLICADA|OTRA|REVISAR/.test(r)?'warn':''}
function render(a,l){const c={};a.forEach(x=>c[x.resultado||'SIN_RESULTADO']=(c[x.resultado||'SIN_RESULTADO']||0)+1);resultCards.innerHTML=Object.entries(c).sort((a,b)=>b[1]-a[1]).slice(0,12).map(([k,v])=>'<div class="card"><strong>'+v+'</strong><span>'+e(k.replaceAll('_',' '))+'</span></div>').join('');resultSub.textContent=l?l.archivo_nombre+' · '+a.length+' servicios':'';results.innerHTML=a.length?a.map(x=>'<tr><td><span class="badge '+cls(x.resultado||'')+'">'+e(x.resultado||'—')+'</span></td><td>'+e(x.codigo_servicio)+'</td><td>'+e(x.cliente)+'</td><td>'+e(x.tipo_conexion)+'</td><td>'+e(x.ip_cliente)+'</td><td>'+e(x.rb_encontrado?((x.rb_comentario||'Encontrado')+' · '+(x.rb_lista||'')):'NO')+'</td><td>'+e(x.huawei_encontrado?((x.huawei_olt_codigo||'')+' · '+(x.huawei_fsp||'')+' · '+(x.huawei_onu_sn||'')):'NO')+'</td><td>'+e(x.detalle||'')+'</td></tr>').join(''):'<tr><td colspan="8">Sin resultados.</td></tr>'}
async function openLote(id){const d=await call({action:'detail',lote_id:id});lote=id;render(d.rows,d.lote);reconcile.disabled=false}
async function history(){const d=await call({action:'list-lotes'});document.getElementById('history').innerHTML=(d.lotes||[]).length?d.lotes.map(x=>'<div class="histItem"><div><b>'+e(x.archivo_nombre)+'</b><small>'+e(x.cargado_por_nombre||'')+' · '+new Date(x.created_at).toLocaleString('es-EC')+' · '+x.filas_total+' servicios · '+e(x.estado)+'</small></div><button class="btn alt" onclick="openLote(\''+x.id+'\').then(()=>show(\'result\')).catch(x=>msg(x.message,\'err\'))">Abrir</button></div>').join(''):'<div class="status">Aún no hay cargas.</div>'}
function show(v){previewView.style.display=v==='preview'?'block':'none';resultView.style.display=v==='result'?'block':'none';document.querySelectorAll('.tab').forEach(b=>b.classList.toggle('on',b.dataset.view===v))}
document.querySelectorAll('.tab').forEach(b=>b.onclick=()=>show(b.dataset.view));history().catch(x=>history.innerHTML='<div class="status err">'+e(x.message)+'</div>');